name: SetWord
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Word
        run: chmod +x ./setWord.sh && ./setWord.sh
        working-directory: .
