name: SetWord
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Word
        run: chmod +x ./setWord.sh && ./setWord.sh
        working-directory: .

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m"Set Word"

      - name: Push
        run: |
           echo TODO