name: SetWord
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push
        working-directory: .
        run: |
          chmod +x ./setWord.sh && ./setWord.sh
          git config --local user.email ${{ secrets.EMAIL_ADDRESS }}
          git config --local user.name ${{ secrets.USER_NAME }}
          git add --all
          git commit -m"Set word"
          git push https://${{ secrets.PAT }}@github.com/adlardco/ana.git